# Generated by Django 5.2.5 on 2025-09-02 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('cereal', 'Cereal/Grain'), ('legume', 'Legume'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('root_tuber', 'Root/Tuber'), ('oil_crop', 'Oil Crop'), ('fodder', 'Fodder/Forage'), ('other', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cropFarmer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
